# Generated by Django 6.0.3 on 2026-04-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя писателя')),
                ('birth_year', models.IntegerField(verbose_name='Год рождения')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Год смерти')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('works', models.TextField(verbose_name='Известные произведения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото')),
                ('epoch', models.CharField(max_length=100, verbose_name='Эпоха/Период')),
            ],
            options={
                'verbose_name': 'Писатель',
                'verbose_name_plural': 'Писатели',
            },
        ),
    ]
