# Generated by Django 6.0.3 on 2026-04-06 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Цитата')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='writers.writer', verbose_name='Жазуучу')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаталар',
            },
        ),
    ]
