# Generated by Django 6.0.3 on 2026-04-06 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0002_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Жанр')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_set', to='writers.writer')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
            },
        ),
    ]
