# Generated by Django 6.0.3 on 2026-05-01 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0003_work'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='works',
        ),
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='writer',
            name='language',
            field=models.CharField(choices=[('kyrgyz', 'Кыргызча'), ('russian', 'Орусча'), ('both', 'Эки тилде')], default='kyrgyz', max_length=20, verbose_name='Язык творчества'),
        ),
        migrations.AddField(
            model_name='writer',
            name='tags',
            field=models.CharField(blank=True, help_text='Например: патриотизм, природа, любовь', max_length=300, verbose_name='Теги (через запятую)'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='writers.writer')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
                'unique_together': {('user', 'writer')},
            },
        ),
    ]
